<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLZxZge2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLZxZge2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLZxZge2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLZxZge2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLZxZge2\App_KernelDevDebugContainer([
    'container.build_hash' => 'LZxZge2',
    'container.build_id' => 'cd4cb514',
    'container.build_time' => 1682088967,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLZxZge2');
